[b] East - Fix/allow uploading webm videos
mirainc/raydiant-kit pull request #174
Opened 2020-10-26 08:29 UTC by VinhVu0412

## Description
- [P2 Bug: Unable to upload webm videos](https://trello.com/c/1d8L450w/2449-p2-bug-unable-to-upload-webm-videos)
- We can drag-n-drop WebM videos to upload them because we set the wrong MIME type.

2020-10-26 15:59 UTC, jschr approved these changes

2020-10-26 16:00 UTC, jschr commented on packages/raydiant-kit/src/prop-types/VideoType.ts
> +  'video/webm',
Could we keep `.webm` and `video/webm` to solve the issue?

2020-10-26 16:11 UTC, jschr commented on packages/raydiant-kit/src/prop-types/VideoType.ts
> +  'video/webm',
I did a quick test and `.webm` seems to work in Firefox, Safari and Chrome:

https://jsfiddle.net/c9qdryfz/1/

What's different?

2020-10-26 16:13 UTC, jschr requested changes
See comment

2020-10-27 09:01 UTC, hgbao-eastagile commented on packages/raydiant-kit/src/prop-types/VideoType.ts
> +  'video/webm',
You were right, `.webm` works fine as a file input's `accept` field.

However, we are defining the available file type here then it should be `video/webm` not `.webm`, because we later use this file type in [mira-dash](https://github.com/mirainc/mira-dash/blob/staging/src/pages/ApplicationsPage/ApplicationsPage.tsx#L193) to detect the MIME type to choose the right app. But when the input reads the file, `file.type` will return `video/webm`, not `.webm`.

So if we keep using `.webm` here, [mira-dash](https://github.com/mirainc/mira-dash/blob/staging/src/pages/ApplicationsPage/ApplicationsPage.tsx#L193)  cannot detect the right app to open => Drag-n-drop will not work

2020-10-27 13:30 UTC, jschr commented on packages/raydiant-kit/src/prop-types/VideoType.ts
> +  'video/webm',
Then I think we should just keep `video/webm`. This sounds like a Safari... and I don't like the workaround so far.

Who reported this bug? Did a customer report it? 

I don't think this is worth fixing as long as you can still select a webm video. Most users don't even upload webm.

2020-10-28 13:55 UTC, jschr approved these changes

2020-10-29 15:39 UTC, merged